/// Flutter icons InstaIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InstaIcons
///      fonts:
///       - asset: fonts/InstaIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class InstaIcons {
  InstaIcons._();

  static const _kFontFam = 'InstaIcons';

  static const IconData group_25 =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData settings =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData contacts =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bookmark =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData mesagge = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData photo = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe81f, fontFamily: _kFontFam);
}
